### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arnold1** [neykov/armboot#2]
Hi,

do you know how much effort it is to support xilix with arm cortex a9?
i also need the startup code right?

Thx,

**Comment by neykov** [comment]
Hi @Arnold1,
Shouldn't be too hard to target a different CPU. There are a couple of things you need to do:
- The initialization code is currently done in C & asm, so you can get it from any existing C project (the memory map - .ld file as well). All you need to do is call into [main](https://github.com/neykov/armboot/blob/master/sys/startup_stm32f4xx.s#L101) function to switch to Rust code
- Describe your architecture in [target.json](https://github.com/neykov/armboot/blob/master/target.json)

**Comment by Arnold1** [comment]
thanks for your reply.

do you know any c project that uses the arm cortex a9?

**Comment by neykov** [comment]
It's really dependant on the development board you are using. You can probably already run Linux on it so better start with a Linux binary and once you have it working move to bare metal. This looks useful for your case - https://github.com/Ogeon/rust-on-raspberry-pi.

**Comment by Arnold1** [comment]
can already run it on linux...
quick question: why is the main function declared as #[no_mangle] pub extern "C" in main.rs?
how can the rust compiler understand the linkerscript stm32_flash.ld and place the variables at the right place in ram?
what is the project template used for, do you plan to use different compilers?

**Comment by neykov** [comment]
https://github.com/geraldstanje/rust-arm-cortex-a9
